# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
# _bind follows the b12x KDA prefill launcher (_run_b12x_kda_prefill) of the GLM-5.3 backport's
# vllm/models/glm5next/nvidia/kda.py (vllm-project/vllm, Apache-2.0).
# Modified by the GLM-5.3 RiNGSiDE recipe (othexmr): b12x's KDA prefill recurrence kernel outside the b12x package with
# a compile-time loop over several checkpoint exports, and prefill pipelines that export the planned KDA states and conv
# history.
"""N-checkpoint KDA prefill for GLM-5.3-Flash (kda-checkpoints lane, 2026-09-24; GENERATED by
outputs/2026-09-24-kda-prefill-checkpoints/build_ckpt_module.py, do not edit by hand).

A prefill chunk exports the KDA recurrent state at several chunk-aligned offsets into their own state slots, so the
scheduler no longer has to end a forward at every position whose state the prefix cache keeps. `_RecurrenceCkptKernel`
is b12x's KDA prefill recurrence kernel (lukealonso/b12x, Apache-2.0; `b12x/sequence/kda_prefill/_cute_kernels.py`,
sha256 1580ca67 in the serving image) with its single checkpoint turned into a compile-time loop over `max_checkpoints`
checkpoints, the change FujitsuPolycom/sparkring made in `runtime/images/sparkring-r35/patches/b12x-sparkring.patch`
@ 90d510a5 (Apache-2.0; see this folder's NOTICE). Modified by the GLM-5.3 lab: the kernel lives outside the b12x
package (b12x's package fingerprint, served kernels and disk cache stay untouched), its compile keys carry this file's
sha256, and the pipeline below reuses b12x's own prologue and prepare launches (trusted metadata validation never reads the checkpoint arrays) or glm53_kda_conv's fused prepare.

Contract: checkpoint slots and offsets are int tensors `[seqs, max_checkpoints]` (slot dtype = the state index dtype),
an offset of 0 or a null slot means "no checkpoint"; offsets are multiples of 16 inside the sequence's rows of this
call; a checkpoint slot is distinct from every final slot and from every other checkpoint slot. The exported recurrent
state is the running fp32 state after the tile that ends at the offset, the bytes a chunk ending there would store.
The conv history of a checkpoint (conv-state rows 0..2 = the three pre-conv q|k|v rows before the offset) is written by
`export_conv_history`; rows 3.. of a checkpoint slot (the spec-decode window) are not written.
"""

from __future__ import annotations

import hashlib
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

import cuda.bindings.driver as cuda
import cutlass
import cutlass.cute as cute
import torch
from cutlass import BFloat16, Float32, Int32, Int64, Uint32

from b12x._lib.compiler import KernelCompileSpec
from b12x._lib.compiler import compile as b12x_compile
from b12x._lib.intrinsics import (
    bf16_mma_m16n8k16_f32,
    cp_async_bulk_g2s_mbar,
    ld_shared_v4_f32,
    ld_shared_v4_u32,
    ldmatrix_m8n8x4_b16,
    ldmatrix_m8n8x4_trans_b16,
    pack_f32x2_to_bfloat2,
    shared_ptr_to_u32,
    st_global_v4_u32,
    st_shared_v4_f32,
)
from b12x._lib.runtime_control import raise_if_kernel_resolution_frozen
from b12x._lib.utils import current_cuda_stream
from b12x.sequence.kda_prefill import _cute_kernels as K
from b12x.sequence.kda_prefill._cute_kernels import (
    _CHUNK,
    _HEAD_DIM,
    _V_PREFETCH_TILES,
    _bf16x2_to_f32x2,
    _cp_async_16_zfill,
    _cp_async_mbarrier_arrive_noinc,
    _ld_acquire_gpu_i32,
    _ld_shared_v2_f32,
    _nanosleep,
    _pointer_address,
    _prefetch_l2,
    _stmatrix_x4_trans,
)
from b12x.sequence.kda_prefill._policy import WorkspaceRecord as REC

_SOURCE_TAG = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()[:16]
_LOG2E = 1.4426950408889634
_RECURRENCE_CKPT_CACHE: dict[tuple, Callable[..., None]] = {}
_WARMED: set[tuple] = set()
MAX_CHECKPOINTS = 8


class _RecurrenceCkptKernel:
    """Per (window, sequence, head, value split): walk the tiles with the state in registers.

    A CTA holds ``v_split`` rows of the transposed state for one head. Its MMA
    warps form ``v_split // 16`` row groups of ``k_split`` warps; each warp owns
    ``128 // k_split`` key columns of its group's sixteen rows as fp32 m16n8
    accumulator fragments plus a bf16 shadow packed as k16 A fragments. Every
    per-tile product reuses the previous accumulator as the next A operand; the
    two products that contract over the key axis are reduced across the
    group's warps through shared memory when ``k_split > 1``. One producer warp
    streams the prepared tiles through a ``stages``-deep shared-memory ring
    with bulk async copies and mbarriers, so the MMA warps never wait on loads
    or on a CTA-wide barrier inside the tile loop.

    One launch covers one window of ``window_tiles`` consecutive banded tile
    positions (see the prologue), so every live sequence advances in every
    window. CTA row ``by`` maps to one sequence rank with positions in the
    window; a sequence that began in an earlier window resumes from its final
    state slot, and one that continues past the window leaves its running
    state there. Empty sequences copy initial to final in window 0. The
    producer polls the per-tile ready flags of the prepare kernel, so the two
    kernels of a window overlap.
    """

    def __init__(
        self,
        *,
        heads: int,
        tiles_capacity: int,
        window_tiles: int,
        rows: int,
        v_split: int,
        k_split: int,
        stages: int,
        checkpoint_export: bool,
        max_checkpoints: int,
        null_state_index: int | None,
        index_type: type[cutlass.Numeric],
    ) -> None:
        self.heads = int(heads)
        self.tiles_capacity = int(tiles_capacity)
        self.window_tiles = int(window_tiles)
        self.rows = int(rows)
        self.v_split = int(v_split)
        self.k_split = int(k_split)
        self.stages = int(stages)
        if self.stages < 2:
            raise ValueError("the recurrence pipeline needs at least two stages")
        if self.k_split not in (1, 2, 4):
            raise ValueError("k_split must be 1, 2, or 4")
        self.splits = _HEAD_DIM // self.v_split
        self.row_groups = self.v_split // 16
        self.mma_warps = self.row_groups * self.k_split
        self.mma_threads = 32 * self.mma_warps
        self.threads = self.mma_threads + 32
        self.cols = _HEAD_DIM // self.k_split
        self.kb_steps = self.cols // 16
        self.nb_blocks = self.cols // 8
        self.checkpoint_export = bool(checkpoint_export)
        # glm53 kda-checkpoints: several checkpoints per sequence (compile-time loop), after SparkRing.
        self.max_checkpoints = int(max_checkpoints)
        if not 1 <= self.max_checkpoints <= 8:
            raise ValueError("max_checkpoints must be in 1..8")
        self.has_null = null_state_index is not None
        self.null_state_index = 0 if null_state_index is None else int(null_state_index)
        self.index_type = index_type
        self.v_chunks_per_row = self.v_split // 8

    @cute.jit
    def __call__(
        self,
        v: cute.Pointer,
        cu_seqlens: cute.Pointer,
        band_base: cute.Pointer,
        sorted_seq: cute.Pointer,
        window_table: cute.Pointer,
        initial_indices: cute.Pointer,
        final_indices: cute.Pointer,
        checkpoint_indices: cute.Pointer,
        checkpoint_offsets: cute.Pointer,
        num_seqs: cute.Pointer,
        error_code: cute.Pointer,
        ready: cute.Pointer,
        ws: cute.Pointer,
        recurrent_state: cute.Pointer,
        output: cute.Pointer,
        v_stride: Int64,
        out_stride: Int64,
        slot_stride: Int64,
        final_stride: Int64,
        token_capacity: Int32,
        window: Int32,
        stream: cuda.CUstream,
    ):
        self.kernel(
            v, cu_seqlens, band_base, sorted_seq, window_table, initial_indices, final_indices,
            checkpoint_indices, checkpoint_offsets, num_seqs, error_code, ready, ws,
            recurrent_state, output, v_stride, out_stride, slot_stride, final_stride,
            token_capacity, window,
        ).launch(
            grid=(self.heads * self.splits, self.rows, 1),
            block=(self.threads, 1, 1),
            stream=stream,
        )

    @cute.jit
    def _is_null(self, slot: Int64) -> cutlass.Boolean:
        result = slot != slot
        if cutlass.const_expr(self.has_null):
            result = slot == Int64(self.null_state_index)
        return result

    @cute.jit
    def _store_state(
        self,
        target: cute.Pointer,
        acc: cute.Tensor,
        base: Int64,
        row0: Int32,
        row1: Int32,
        col_base: Int32,
        tid: Int32,
    ):
        for nb in cutlass.range_constexpr(self.nb_blocks):
            kcol = col_base + Int32(nb * 8) + tid * Int32(2)
            offset0 = base + row0.to(Int64) * Int64(_HEAD_DIM) + kcol.to(Int64)
            offset1 = base + row1.to(Int64) * Int64(_HEAD_DIM) + kcol.to(Int64)
            target[offset0] = acc[nb, 0]
            target[offset0 + Int64(1)] = acc[nb, 1]
            target[offset1] = acc[nb, 2]
            target[offset1 + Int64(1)] = acc[nb, 3]

    @cute.jit
    def _load_state(
        self,
        source: cute.Pointer,
        acc: cute.Tensor,
        base: Int64,
        row0: Int32,
        row1: Int32,
        col_base: Int32,
        tid: Int32,
    ):
        for nb in cutlass.range_constexpr(self.nb_blocks):
            kcol = col_base + Int32(nb * 8) + tid * Int32(2)
            offset0 = base + row0.to(Int64) * Int64(_HEAD_DIM) + kcol.to(Int64)
            offset1 = base + row1.to(Int64) * Int64(_HEAD_DIM) + kcol.to(Int64)
            acc[nb, 0] = Float32(source[offset0])
            acc[nb, 1] = Float32(source[offset0 + Int64(1)])
            acc[nb, 2] = Float32(source[offset1])
            acc[nb, 3] = Float32(source[offset1 + Int64(1)])

    @cute.jit
    def _refresh_shadow(self, acc: cute.Tensor, shadow: cute.Tensor):
        for kb in cutlass.range_constexpr(self.kb_steps):
            shadow[kb, 0] = pack_f32x2_to_bfloat2(acc[2 * kb, 0], acc[2 * kb, 1])
            shadow[kb, 1] = pack_f32x2_to_bfloat2(acc[2 * kb, 2], acc[2 * kb, 3])
            shadow[kb, 2] = pack_f32x2_to_bfloat2(acc[2 * kb + 1, 0], acc[2 * kb + 1, 1])
            shadow[kb, 3] = pack_f32x2_to_bfloat2(acc[2 * kb + 1, 2], acc[2 * kb + 1, 3])

    @cute.jit
    def _issue_tile(
        self,
        ws: cute.Pointer,
        v: cute.Pointer,
        stage_addr: Int32,
        ring_index: Int32,
        head: Int32,
        token_base: Int32,
        rows_live: Int32,
        head_elements: Int64,
        split_elements: Int64,
        v_stride: Int64,
        full_bar_u32: Int32,
        full_bar_ptr: cute.Pointer,
        lane: Int32,
    ):
        """Issue the copies of ring record ``ring_index`` and its value rows into a stage.

        Every lane copies its share of the ``[16 x v_split]`` value rows with
        16-byte cp.async (zero-filled past the live rows) into the stage's
        sixteen-column-group layout and arrives on the stage barrier when
        they land; lane 0 then posts the record head's byte count and copies
        it with one bulk copy. The barrier expects the 32 lane arrivals plus
        lane 0's, so the phase cannot complete before every value row landed.
        """
        vd = self.v_split
        record = ring_index.to(Int64) * Int64(self.heads) + head.to(Int64)
        record_base = record * Int64(REC.BYTES)
        chunks_per_row = vd // 8
        v_addr = stage_addr + Int32(REC.V)
        for item in cutlass.range_constexpr((_CHUNK * chunks_per_row) // 32):
            chunk = lane + Int32(item * 32)
            row = chunk // Int32(chunks_per_row)
            col8 = chunk % Int32(chunks_per_row)
            src_bytes = Int32(16)
            if row >= rows_live:
                src_bytes = Int32(0)
            live_row = cutlass.min(row, cutlass.max(rows_live - Int32(1), Int32(0)))
            element = (token_base + live_row).to(Int64) * v_stride + head_elements + split_elements + (col8 * Int32(8)).to(Int64)
            dst = v_addr + (col8 >> Int32(1)) * Int32(512) + row * Int32(32) + (col8 & Int32(1)) * Int32(16)
            _cp_async_16_zfill(dst, _pointer_address(v, element), src_bytes)
        _cp_async_mbarrier_arrive_noinc(full_bar_u32)
        if lane == Int32(0):
            cute.arch.fence_acq_rel_cta()
            cute.arch.mbarrier_arrive_and_expect_tx(full_bar_ptr, Int32(REC.HEAD_BYTES))
            # Orders the async-proxy copy after the acquire of the ready flag.
            cute.arch.fence_proxy("async.global")
            cp_async_bulk_g2s_mbar(
                stage_addr, _pointer_address(ws, record_base), Int32(REC.HEAD_BYTES), full_bar_u32
            )

    @cute.jit
    def _group_reduce(
        self,
        partial: cute.Tensor,
        red_addr: Int32,
        group: Int32,
        kq: Int32,
        lane: Int32,
    ):
        """Sum a [16 x 16] fp32 fragment across the group's warps."""
        slot = (group * Int32(self.k_split) + kq) * Int32(256) + lane * Int32(8)
        mine = red_addr + slot * Int32(4)
        st_shared_v4_f32(mine, partial[0, 0], partial[0, 1], partial[0, 2], partial[0, 3])
        st_shared_v4_f32(mine + Int32(16), partial[1, 0], partial[1, 1], partial[1, 2], partial[1, 3])
        cute.arch.barrier(barrier_id=1, number_of_threads=self.mma_threads)
        for other in cutlass.range_constexpr(self.k_split):
            if Int32(other) != kq:
                theirs = red_addr + ((group * Int32(self.k_split) + Int32(other)) * Int32(256) + lane * Int32(8)) * Int32(4)
                a0, a1, a2, a3 = ld_shared_v4_f32(theirs)
                b0, b1, b2, b3 = ld_shared_v4_f32(theirs + Int32(16))
                partial[0, 0] += a0
                partial[0, 1] += a1
                partial[0, 2] += a2
                partial[0, 3] += a3
                partial[1, 0] += b0
                partial[1, 1] += b1
                partial[1, 2] += b2
                partial[1, 3] += b3

    @cute.kernel
    def kernel(
        self,
        v: cute.Pointer,
        cu_seqlens: cute.Pointer,
        band_base: cute.Pointer,
        sorted_seq: cute.Pointer,
        window_table: cute.Pointer,
        initial_indices: cute.Pointer,
        final_indices: cute.Pointer,
        checkpoint_indices: cute.Pointer,
        checkpoint_offsets: cute.Pointer,
        num_seqs: cute.Pointer,
        error_code: cute.Pointer,
        ready: cute.Pointer,
        ws: cute.Pointer,
        recurrent_state: cute.Pointer,
        output: cute.Pointer,
        v_stride: Int64,
        out_stride: Int64,
        slot_stride: Int64,
        final_stride: Int64,
        token_capacity: Int32,
        window: Int32,
    ):
        bx, by, _ = cute.arch.block_idx()
        thread, _, _ = cute.arch.thread_idx()
        thread = Int32(thread)
        head = Int32(bx) // Int32(self.splits)
        split = Int32(bx) % Int32(self.splits)
        warp = thread // Int32(32)
        lane = Int32(cute.arch.lane_idx())
        gid = lane >> Int32(2)
        tid = lane & Int32(3)
        matrix = lane >> Int32(3)
        matrix_row = lane & Int32(7)
        is_producer = warp == Int32(self.mma_warps)
        group = cutlass.min(warp, Int32(self.mma_warps - 1)) // Int32(self.k_split)
        kq = cutlass.min(warp, Int32(self.mma_warps - 1)) % Int32(self.k_split)
        col_base = kq * Int32(self.cols)
        chunk_base = kq * Int32(self.nb_blocks)
        group_lead = kq == Int32(0)
        if cutlass.const_expr(self.k_split == 1):
            group_lead = cutlass.Boolean(True)
        error = error_code[Int32(0)].to(Int32)
        live_seqs = num_seqs[Int32(0)].to(Int32)
        vd = self.v_split
        if error != Int32(0):
            # Transactional failure: poison every output row of this CTA's
            # value columns; no state is written.
            if (window == Int32(0)) & (Int32(by) == Int32(0)):
                nan_pair = Uint32(0x7FC07FC0)
                chunk = thread
                while chunk < token_capacity * Int32(self.v_chunks_per_row):
                    row = chunk // Int32(self.v_chunks_per_row)
                    col_chunk = chunk % Int32(self.v_chunks_per_row)
                    element = (
                        row.to(Int64) * out_stride
                        + head.to(Int64) * Int64(_HEAD_DIM)
                        + (split * Int32(vd) + col_chunk * Int32(8)).to(Int64)
                    )
                    st_global_v4_u32(
                        _pointer_address(output, element), nan_pair, nan_pair, nan_pair, nan_pair
                    )
                    chunk += Int32(self.threads)
        else:
            window_begin = window * Int32(self.window_tiles)
            window_end = window_begin + Int32(self.window_tiles)
            total_tiles = band_base[Int32(self.tiles_capacity + 1)].to(Int32)
            tiled_seqs = band_base[Int32(1)].to(Int32)
            # The band holding the window's first position and the rank of
            # that position within it (from the prologue's window table).
            # Rows first cover the ranks from there to the end of that band,
            # then the ranks before it, which reach the window in the next
            # band.
            band_a = window_table[window * Int32(2)].to(Int32)
            first_rank = window_table[window * Int32(2) + Int32(1)].to(Int32)
            seg1 = band_base[band_a + Int32(1)].to(Int32) - window_begin
            if window_begin >= total_tiles:
                first_rank = Int32(0)
                seg1 = Int32(0)
            rank = Int32(-1)
            l_begin = Int32(0)
            if Int32(by) < seg1:
                rank = first_rank + Int32(by)
                l_begin = band_a
            elif Int32(by) - seg1 < first_rank:
                rank = Int32(by) - seg1
                l_begin = band_a + Int32(1)
            seq = Int32(0)
            start = Int32(0)
            end = Int32(0)
            tiles_s = Int32(0)
            l_end = Int32(0)
            if rank >= Int32(0):
                seq = sorted_seq[rank].to(Int32)
                start = cu_seqlens[seq].to(Int32)
                end = cu_seqlens[seq + Int32(1)].to(Int32)
                tiles_s = cutlass.min(
                    (cutlass.max(Int32(0), end - start) + Int32(_CHUNK - 1)) // Int32(_CHUNK),
                    Int32(self.tiles_capacity),
                )
                l_begin = cutlass.min(l_begin, tiles_s)
            stage_bytes = REC.V + vd * 32
            allocator = cutlass.utils.SmemAllocator()
            # Band positions of this CTA's local tiles l_begin .. l_begin + WT.
            s_band = allocator.allocate_tensor(
                element_type=Int32,
                layout=cute.make_layout((self.window_tiles + 1,), stride=(1,)),
                byte_alignment=16,
            )
            s_stage = allocator.allocate_tensor(
                element_type=cutlass.Int8,
                layout=cute.make_layout((self.stages * stage_bytes,), stride=(1,)),
                byte_alignment=128,
            )
            s_out = allocator.allocate_tensor(
                element_type=BFloat16,
                layout=cute.make_layout((_CHUNK * vd,), stride=(1,)),
                byte_alignment=128,
            )
            # Cross-warp reduction buffers, only with a key split.
            s_red = allocator.allocate_tensor(
                element_type=Float32,
                layout=cute.make_layout((2 * self.mma_warps * 256 if self.k_split > 1 else 4,), stride=(1,)),
                byte_alignment=128,
            )
            mbar = allocator.allocate_tensor(
                element_type=Int64,
                layout=cute.make_layout((2 * self.stages,), stride=(1,)),
                byte_alignment=8,
            )
            stage_base = shared_ptr_to_u32(s_stage.iterator)
            out_addr = shared_ptr_to_u32(s_out.iterator)
            red_base = shared_ptr_to_u32(s_red.iterator)
            red_a = red_base
            red_c = red_base + Int32(self.mma_warps * 256 * 4)
            full_bar = mbar.iterator
            empty_bar = mbar.iterator + self.stages
            if thread == Int32(0):
                for stage_index in cutlass.range_constexpr(self.stages):
                    cute.arch.mbarrier_init(full_bar + stage_index, Int32(33))
                    cute.arch.mbarrier_init(empty_bar + stage_index, Int32(self.mma_warps))
            if rank >= Int32(0):
                entry = thread
                while entry < Int32(self.window_tiles + 1):
                    band = cutlass.min(l_begin + entry, Int32(self.tiles_capacity + 1))
                    s_band[entry] = band_base[band].to(Int32)
                    entry += Int32(self.threads)
            cute.arch.sync_threads()
            # Last local tile of this window: the first band whose position
            # reaches the window end (at most WT bands lie in a window).
            l_end = l_begin
            if rank >= Int32(0):
                # Smallest staged entry whose position reaches the window end;
                # entries past the sequence's tiles are excluded by the clamp.
                span = cutlass.min(tiles_s - l_begin, Int32(self.window_tiles))
                low = Int32(0)
                high = span
                while high > low:
                    mid = (low + high) >> Int32(1)
                    if s_band[mid] + rank >= window_end:
                        high = mid
                    else:
                        low = mid + Int32(1)
                l_end = l_begin + low
            has_tiles = l_end > l_begin

            head_elements = head.to(Int64) * Int64(_HEAD_DIM)
            split_elements = (split * Int32(vd)).to(Int64)
            v_chunks = self.v_chunks_per_row
            ring_base = (window & Int32(1)) * Int32(self.window_tiles) - window_begin + rank
            expected_flag = window + Int32(1)
            head_base = head.to(Int64) * Int64(_HEAD_DIM * _HEAD_DIM)

            if is_producer:
                # Producer: refill ring stages as they free up, once the
                # prepare kernel has published the tile. Lane 0 waits and
                # polls; every lane then issues its share of the copies.
                prod_phase = Int32(1)
                count = Int32(0)
                if has_tiles:
                    # The flag of the next tile is read right after the copies
                    # of the current one are issued, so its latency overlaps the
                    # wait for a free stage; a stale value falls back to a spin.
                    seen = Int32(0)
                    if lane == Int32(0):
                        first_flag = _pointer_address(
                            ready, (ring_base + s_band[Int32(0)]).to(Int64) * Int64(self.heads) + head.to(Int64)
                        )
                        seen = _ld_acquire_gpu_i32(first_flag)
                    for step in cutlass.range(l_end - l_begin, unroll=1):
                        local = l_begin + step
                        stage = count % Int32(self.stages)
                        ring_index = ring_base + s_band[step]
                        if lane == Int32(0):
                            cute.arch.mbarrier_wait(empty_bar + stage, phase=prod_phase)
                        if lane == Int32(0):
                            flag = _pointer_address(
                                ready, ring_index.to(Int64) * Int64(self.heads) + head.to(Int64)
                            )
                            while seen != expected_flag:
                                _nanosleep(Int32(128))
                                seen = _ld_acquire_gpu_i32(flag)
                        cute.arch.sync_warp()
                        token_base = start + local * Int32(_CHUNK)
                        rows_live = cutlass.min(Int32(_CHUNK), end - token_base)
                        self._issue_tile(
                            ws, v, stage_base + stage * Int32(stage_bytes), ring_index, head,
                            token_base, rows_live, head_elements, split_elements, v_stride,
                            shared_ptr_to_u32(full_bar + stage), full_bar + stage, lane,
                        )
                        if lane == Int32(0):
                            if step + Int32(1) < l_end - l_begin:
                                next_flag = _pointer_address(
                                    ready,
                                    (ring_base + s_band[step + Int32(1)]).to(Int64) * Int64(self.heads)
                                    + head.to(Int64),
                                )
                                seen = _ld_acquire_gpu_i32(next_flag)
                        # Warm L2 with the value rows of a tile a few steps
                        # ahead: one lane per row, one line per v_split * 2 bytes.
                        ahead = local + Int32(_V_PREFETCH_TILES)
                        if ahead < l_end:
                            if lane < Int32(_CHUNK):
                                row_token = start + ahead * Int32(_CHUNK) + lane
                                if row_token < end:
                                    line = row_token.to(Int64) * v_stride + head_elements + split_elements
                                    for part in cutlass.range_constexpr(max(1, (self.v_split * 2) // 128)):
                                        _prefetch_l2(_pointer_address(v, line + Int64(part * 64)))
                        if stage == Int32(self.stages - 1):
                            prod_phase = prod_phase ^ Int32(1)
                        count += Int32(1)
            else:
                # State fragments: rows row0/row1, columns col_base.. of this head.
                row_local0 = group * Int32(16) + gid
                row0 = split * Int32(vd) + row_local0
                row1 = row0 + Int32(8)
                acc = cute.make_rmem_tensor((self.nb_blocks, 4), Float32)
                shadow = cute.make_rmem_tensor((self.kb_steps, 4), Uint32)
                parts = cute.make_rmem_tensor((4, 4), Float32)
                bfrag = cute.make_rmem_tensor((self.kb_steps, 4), Uint32)
                lam = cute.make_rmem_tensor((self.nb_blocks, 2), Float32)
                vp = cute.make_rmem_tensor((2, 4), Float32)
                u = cute.make_rmem_tensor((2, 4), Float32)
                out = cute.make_rmem_tensor((2, 4), Float32)
                cons_phase = Int32(0)
                count = Int32(0)
                if has_tiles:
                    initial = Int64(initial_indices[seq])
                    final = Int64(final_indices[seq.to(Int64) * final_stride])
                    for nb in cutlass.range_constexpr(self.nb_blocks):
                        acc[nb, 0] = Float32(0.0)
                        acc[nb, 1] = Float32(0.0)
                        acc[nb, 2] = Float32(0.0)
                        acc[nb, 3] = Float32(0.0)
                    if l_begin == Int32(0):
                        if not self._is_null(initial):
                            self._load_state(
                                recurrent_state, acc, initial * slot_stride + head_base,
                                row0, row1, col_base, tid,
                            )
                    else:
                        # Resume the running state left in the final slot.
                        self._load_state(
                            recurrent_state, acc, final * slot_stride + head_base,
                            row0, row1, col_base, tid,
                        )
                    self._refresh_shadow(acc, shadow)
                    # The guard is load-bearing: the loop body and its zero
                    # trip count are the same without it, but the generated
                    # schedule is far worse (the sixteen-head 4096-token case
                    # measures 428 us instead of 220 us on RTX PRO 6000).
                    if has_tiles:
                        for step in cutlass.range(l_end - l_begin, unroll=1):
                            local = l_begin + step
                            stage = count % Int32(self.stages)
                            token_base = start + local * Int32(_CHUNK)
                            rows_live = cutlass.min(Int32(_CHUNK), end - token_base)
                            cute.arch.mbarrier_wait(full_bar + stage, phase=cons_phase)
                            stage_addr = stage_base + stage * Int32(stage_bytes)
                            qt_addr = stage_addr + Int32(REC.Q_TILDE)
                            kt_addr = stage_addr + Int32(REC.K_TILDE)
                            kr_addr = stage_addr + Int32(REC.K_R)
                            inv_addr = stage_addr + Int32(REC.INV)
                            mqk_addr = stage_addr + Int32(REC.MQK)
                            lam_addr = stage_addr + Int32(REC.LAMBDA_C)
                            beta_addr = stage_addr + Int32(REC.BETA)
                            v_addr = stage_addr + Int32(REC.V)

                            # Phase A: partial v'^T over this warp's key columns.
                            # Every operand of the phase is loaded first; the
                            # sixteen products run as four accumulator chains
                            # whose dependent steps are four issues apart.
                            tok_a = (matrix >> Int32(1)) * Int32(8) + matrix_row
                            for kb in cutlass.range_constexpr(self.kb_steps):
                                logical_chunk = chunk_base + Int32(kb * 2) + (matrix & Int32(1))
                                physical = logical_chunk ^ (tok_a & Int32(7))
                                bfrag[kb, 0], bfrag[kb, 1], bfrag[kb, 2], bfrag[kb, 3] = ldmatrix_m8n8x4_b16(
                                    kt_addr + tok_a * Int32(256) + physical * Int32(16)
                                )
                            # v^T in accumulator layout: one transposed ldmatrix of the
                            # group's sixteen value columns (rows tok, cols v).
                            v_tok = (matrix & Int32(1)) * Int32(8) + matrix_row
                            v_col = group * Int32(16) + (matrix >> Int32(1)) * Int32(8)
                            r0, r1, r2, r3 = ldmatrix_m8n8x4_trans_b16(
                                v_addr + group * Int32(512) + v_tok * Int32(32) + (matrix >> Int32(1)) * Int32(16)
                            )
                            beta_lo = beta_addr + tid * Int32(8)
                            beta00, beta01 = _ld_shared_v2_f32(beta_lo)
                            beta10, beta11 = _ld_shared_v2_f32(beta_lo + Int32(32))
                            square_row = (matrix >> Int32(1)) * Int32(8) + matrix_row
                            square_addr = square_row * Int32(32) + (matrix & Int32(1)) * Int32(16)
                            inv0, inv1, inv2, inv3 = ldmatrix_m8n8x4_b16(inv_addr + square_addr)
                            for chain in cutlass.range_constexpr(4):
                                for item in cutlass.range_constexpr(4):
                                    parts[chain, item] = Float32(0.0)
                            for kb in cutlass.range_constexpr(self.kb_steps):
                                for half in cutlass.range_constexpr(2):
                                    chain = 2 * (kb % 2) + half
                                    parts[chain, 0], parts[chain, 1], parts[chain, 2], parts[chain, 3] = (
                                        bf16_mma_m16n8k16_f32(
                                            parts[chain, 0], parts[chain, 1], parts[chain, 2], parts[chain, 3],
                                            shadow[kb, 0], shadow[kb, 1], shadow[kb, 2], shadow[kb, 3],
                                            bfrag[kb, 2 * half], bfrag[kb, 2 * half + 1],
                                        )
                                    )
                            for half in cutlass.range_constexpr(2):
                                for item in cutlass.range_constexpr(4):
                                    vp[half, item] = parts[half, item] + parts[2 + half, item]
                            if cutlass.const_expr(self.k_split > 1):
                                self._group_reduce(vp, red_a, group, kq, lane)
                            v00, v01 = _bf16x2_to_f32x2(r0)
                            v10, v11 = _bf16x2_to_f32x2(r1)
                            v02, v03 = _bf16x2_to_f32x2(r2)
                            v12, v13 = _bf16x2_to_f32x2(r3)
                            vp[0, 0] = (v00 - vp[0, 0]) * beta00
                            vp[0, 1] = (v01 - vp[0, 1]) * beta01
                            vp[0, 2] = (v02 - vp[0, 2]) * beta00
                            vp[0, 3] = (v03 - vp[0, 3]) * beta01
                            vp[1, 0] = (v10 - vp[1, 0]) * beta10
                            vp[1, 1] = (v11 - vp[1, 1]) * beta11
                            vp[1, 2] = (v12 - vp[1, 2]) * beta10
                            vp[1, 3] = (v13 - vp[1, 3]) * beta11
                            a_vp0 = pack_f32x2_to_bfloat2(vp[0, 0], vp[0, 1])
                            a_vp1 = pack_f32x2_to_bfloat2(vp[0, 2], vp[0, 3])
                            a_vp2 = pack_f32x2_to_bfloat2(vp[1, 0], vp[1, 1])
                            a_vp3 = pack_f32x2_to_bfloat2(vp[1, 2], vp[1, 3])

                            # Phase B: U^T = v'^T INV^T (every warp of the group).
                            u[0, 0], u[0, 1], u[0, 2], u[0, 3] = bf16_mma_m16n8k16_f32(
                                Float32(0.0), Float32(0.0), Float32(0.0), Float32(0.0),
                                a_vp0, a_vp1, a_vp2, a_vp3, inv0, inv1,
                            )
                            u[1, 0], u[1, 1], u[1, 2], u[1, 3] = bf16_mma_m16n8k16_f32(
                                Float32(0.0), Float32(0.0), Float32(0.0), Float32(0.0),
                                a_vp0, a_vp1, a_vp2, a_vp3, inv2, inv3,
                            )
                            a_u0 = pack_f32x2_to_bfloat2(u[0, 0], u[0, 1])
                            a_u1 = pack_f32x2_to_bfloat2(u[0, 2], u[0, 3])
                            a_u2 = pack_f32x2_to_bfloat2(u[1, 0], u[1, 1])
                            a_u3 = pack_f32x2_to_bfloat2(u[1, 2], u[1, 3])

                            # Phase C: out^T = U^T Mqk^T + S^T q~^T over this warp's
                            # columns. The U^T Mqk^T product seeds two of the four
                            # chains (kq == 0 only); the rest is as in phase A.
                            for kb in cutlass.range_constexpr(self.kb_steps):
                                logical_chunk = chunk_base + Int32(kb * 2) + (matrix & Int32(1))
                                physical = logical_chunk ^ (tok_a & Int32(7))
                                bfrag[kb, 0], bfrag[kb, 1], bfrag[kb, 2], bfrag[kb, 3] = ldmatrix_m8n8x4_b16(
                                    qt_addr + tok_a * Int32(256) + physical * Int32(16)
                                )
                            for chain in cutlass.range_constexpr(4):
                                for item in cutlass.range_constexpr(4):
                                    parts[chain, item] = Float32(0.0)
                            if group_lead:
                                b0, b1, b2, b3 = ldmatrix_m8n8x4_b16(mqk_addr + square_addr)
                                parts[0, 0], parts[0, 1], parts[0, 2], parts[0, 3] = bf16_mma_m16n8k16_f32(
                                    Float32(0.0), Float32(0.0), Float32(0.0), Float32(0.0),
                                    a_u0, a_u1, a_u2, a_u3, b0, b1,
                                )
                                parts[1, 0], parts[1, 1], parts[1, 2], parts[1, 3] = bf16_mma_m16n8k16_f32(
                                    Float32(0.0), Float32(0.0), Float32(0.0), Float32(0.0),
                                    a_u0, a_u1, a_u2, a_u3, b2, b3,
                                )
                            for kb in cutlass.range_constexpr(self.kb_steps):
                                for half in cutlass.range_constexpr(2):
                                    chain = 2 * (kb % 2) + half
                                    parts[chain, 0], parts[chain, 1], parts[chain, 2], parts[chain, 3] = (
                                        bf16_mma_m16n8k16_f32(
                                            parts[chain, 0], parts[chain, 1], parts[chain, 2], parts[chain, 3],
                                            shadow[kb, 0], shadow[kb, 1], shadow[kb, 2], shadow[kb, 3],
                                            bfrag[kb, 2 * half], bfrag[kb, 2 * half + 1],
                                        )
                                    )
                            for half in cutlass.range_constexpr(2):
                                for item in cutlass.range_constexpr(4):
                                    out[half, item] = parts[half, item] + parts[2 + half, item]
                            if cutlass.const_expr(self.k_split > 1):
                                self._group_reduce(out, red_c, group, kq, lane)
                            if group_lead:
                                # out^T fragments -> s_out[tok][v] through stmatrix.trans,
                                # then the live rows go out as 16-byte chunks, one per
                                # lane; the store's latency overlaps phase D.
                                _stmatrix_x4_trans(
                                    out_addr + (v_tok * Int32(vd) + v_col) * Int32(2),
                                    pack_f32x2_to_bfloat2(out[0, 0], out[0, 1]),
                                    pack_f32x2_to_bfloat2(out[1, 0], out[1, 1]),
                                    pack_f32x2_to_bfloat2(out[0, 2], out[0, 3]),
                                    pack_f32x2_to_bfloat2(out[1, 2], out[1, 3]),
                                )
                                cute.arch.sync_warp()
                                store_row = lane >> Int32(1)
                                store_chunk = group * Int32(2) + (lane & Int32(1))
                                if store_row < rows_live:
                                    c0, c1, c2, c3 = ld_shared_v4_u32(
                                        out_addr + (store_row * Int32(v_chunks) + store_chunk) * Int32(16)
                                    )
                                    element = (
                                        (token_base + store_row).to(Int64) * out_stride
                                        + head_elements
                                        + split_elements
                                        + (store_chunk * Int32(8)).to(Int64)
                                    )
                                    st_global_v4_u32(_pointer_address(output, element), c0, c1, c2, c3)

                            # Phase D: S^T <- S^T * lambda_c[k] + U^T k_r over this warp's columns.
                            tok_d = (matrix & Int32(1)) * Int32(8) + matrix_row
                            for pair in cutlass.range_constexpr(self.nb_blocks // 2):
                                logical_chunk = chunk_base + Int32(pair * 2) + (matrix >> Int32(1))
                                physical = logical_chunk ^ (tok_d & Int32(7))
                                bfrag[pair, 0], bfrag[pair, 1], bfrag[pair, 2], bfrag[pair, 3] = (
                                    ldmatrix_m8n8x4_trans_b16(
                                        kr_addr + tok_d * Int32(256) + physical * Int32(16)
                                    )
                                )
                            for nb in cutlass.range_constexpr(self.nb_blocks):
                                kcol = col_base + Int32(nb * 8) + tid * Int32(2)
                                lam[nb, 0], lam[nb, 1] = _ld_shared_v2_f32(lam_addr + kcol * Int32(4))
                            # Pair p: scale its two blocks, issue their MMAs, then
                            # refresh the shadow of pair p - 2 (whose MMAs are done).
                            pairs = self.nb_blocks // 2
                            for pair in cutlass.range_constexpr(pairs):
                                for nb in cutlass.range_constexpr(2 * pair, 2 * pair + 2):
                                    acc[nb, 0] = acc[nb, 0] * lam[nb, 0]
                                    acc[nb, 1] = acc[nb, 1] * lam[nb, 1]
                                    acc[nb, 2] = acc[nb, 2] * lam[nb, 0]
                                    acc[nb, 3] = acc[nb, 3] * lam[nb, 1]
                                acc[2 * pair, 0], acc[2 * pair, 1], acc[2 * pair, 2], acc[2 * pair, 3] = (
                                    bf16_mma_m16n8k16_f32(
                                        acc[2 * pair, 0], acc[2 * pair, 1], acc[2 * pair, 2], acc[2 * pair, 3],
                                        a_u0, a_u1, a_u2, a_u3, bfrag[pair, 0], bfrag[pair, 1],
                                    )
                                )
                                (
                                    acc[2 * pair + 1, 0],
                                    acc[2 * pair + 1, 1],
                                    acc[2 * pair + 1, 2],
                                    acc[2 * pair + 1, 3],
                                ) = bf16_mma_m16n8k16_f32(
                                    acc[2 * pair + 1, 0], acc[2 * pair + 1, 1],
                                    acc[2 * pair + 1, 2], acc[2 * pair + 1, 3],
                                    a_u0, a_u1, a_u2, a_u3, bfrag[pair, 2], bfrag[pair, 3],
                                )
                                if cutlass.const_expr(pair >= 2):
                                    done = pair - 2
                                    shadow[done, 0] = pack_f32x2_to_bfloat2(acc[2 * done, 0], acc[2 * done, 1])
                                    shadow[done, 1] = pack_f32x2_to_bfloat2(acc[2 * done, 2], acc[2 * done, 3])
                                    shadow[done, 2] = pack_f32x2_to_bfloat2(acc[2 * done + 1, 0], acc[2 * done + 1, 1])
                                    shadow[done, 3] = pack_f32x2_to_bfloat2(acc[2 * done + 1, 2], acc[2 * done + 1, 3])
                            for done in cutlass.range_constexpr(max(0, pairs - 2), pairs):
                                shadow[done, 0] = pack_f32x2_to_bfloat2(acc[2 * done, 0], acc[2 * done, 1])
                                shadow[done, 1] = pack_f32x2_to_bfloat2(acc[2 * done, 2], acc[2 * done, 3])
                                shadow[done, 2] = pack_f32x2_to_bfloat2(acc[2 * done + 1, 0], acc[2 * done + 1, 1])
                                shadow[done, 3] = pack_f32x2_to_bfloat2(acc[2 * done + 1, 2], acc[2 * done + 1, 3])
                            # Every read of this stage is done: release it to the producer.
                            cute.arch.sync_warp()
                            if lane == Int32(0):
                                cute.arch.mbarrier_arrive(empty_bar + stage)
                            if stage == Int32(self.stages - 1):
                                cons_phase = cons_phase ^ Int32(1)
                            count += Int32(1)

                            if cutlass.const_expr(self.checkpoint_export):
                                # glm53 kda-checkpoints (after SparkRing): max_checkpoints (slot, offset) pairs
                                # per sequence, row-major [seqs, max_checkpoints].
                                for cp in cutlass.range_constexpr(self.max_checkpoints):
                                    cp_index = seq * Int32(self.max_checkpoints) + Int32(cp)
                                    checkpoint = Int64(checkpoint_indices[cp_index])
                                    offset = checkpoint_offsets[cp_index].to(Int32)
                                    if (offset > Int32(0)) & ((local + Int32(1)) * Int32(_CHUNK) == offset):
                                        if not self._is_null(checkpoint):
                                            self._store_state(
                                                recurrent_state, acc, checkpoint * slot_stride + head_base,
                                                row0, row1, col_base, tid,
                                            )
                        # Final state, or the running state for the next window.
                        if not self._is_null(final):
                            self._store_state(
                                recurrent_state, acc, final * slot_stride + head_base,
                                row0, row1, col_base, tid,
                            )
                # Empty sequences (ranks past the tiled ones) copy initial to
                # final in window 0.
                if window == Int32(0):
                    empty_rank = tiled_seqs + Int32(by)
                    while empty_rank < live_seqs:
                        empty_seq = sorted_seq[empty_rank].to(Int32)
                        empty_initial = Int64(initial_indices[empty_seq])
                        empty_final = Int64(
                            final_indices[empty_seq.to(Int64) * final_stride]
                        )
                        if not self._is_null(empty_final):
                            for nb in cutlass.range_constexpr(self.nb_blocks):
                                acc[nb, 0] = Float32(0.0)
                                acc[nb, 1] = Float32(0.0)
                                acc[nb, 2] = Float32(0.0)
                                acc[nb, 3] = Float32(0.0)
                            if not self._is_null(empty_initial):
                                self._load_state(
                                    recurrent_state, acc, empty_initial * slot_stride + head_base,
                                    row0, row1, col_base, tid,
                                )
                            self._store_state(
                                recurrent_state, acc, empty_final * slot_stride + head_base,
                                row0, row1, col_base, tid,
                            )
                        empty_rank += Int32(self.rows)


@dataclass
class Checkpoints:
    """One call's checkpoint plan on the device.

    slots/offsets: [seqs, max_checkpoints] (slot dtype = the binding's state index dtype, offsets int32; unused
    entries: offset 0 and the null slot). conv_rows/conv_slots: int64 [n] and [n] pairs for the conv history, three
    per checkpoint (rows are absolute row indices of the call's pre-conv q|k|v rows), or None to skip the conv export.
    """

    slots: torch.Tensor
    offsets: torch.Tensor
    max_checkpoints: int
    conv_rows: torch.Tensor | None = None
    conv_slots: torch.Tensor | None = None
    conv_cols: torch.Tensor | None = None


def _recurrence_ckpt_key(binding, max_checkpoints: int) -> tuple[object, ...]:
    caps = binding.plan.caps
    plan = binding.plan
    return (
        "recurrence_ckpt",
        _SOURCE_TAG,
        binding.output.device.index,
        caps.heads,
        caps.tiles_capacity,
        plan.window_tiles,
        plan.max_windows,
        plan.recurrence_rows,
        plan.v_split,
        plan.k_split,
        plan.stages,
        int(max_checkpoints),
        caps.null_state_index,
        binding.initial_state_indices.dtype,
    )


def _compile_recurrence_ckpt(binding, max_checkpoints: int):
    key = _recurrence_ckpt_key(binding, max_checkpoints)
    cached = _RECURRENCE_CKPT_CACHE.get(key)
    if cached is not None:
        return key, cached
    caps = binding.plan.caps
    index_type = K._numeric_type(binding.initial_state_indices.dtype)
    kernel = _RecurrenceCkptKernel(
        heads=caps.heads,
        tiles_capacity=caps.tiles_capacity,
        window_tiles=binding.plan.window_tiles,
        rows=binding.plan.recurrence_rows,
        v_split=binding.plan.v_split,
        k_split=binding.plan.k_split,
        stages=binding.plan.stages,
        checkpoint_export=True,
        max_checkpoints=int(max_checkpoints),
        null_state_index=caps.null_state_index,
        index_type=index_type,
    )
    raise_if_kernel_resolution_frozen("cute.compile", target=kernel, cache_key=key)
    raw = b12x_compile(
        kernel,
        K._fake_pointer(BFloat16),
        K._fake_pointer(Int32),
        K._fake_pointer(Int32),
        K._fake_pointer(Int32),
        K._fake_pointer(Int32),
        K._fake_pointer(index_type),
        K._fake_pointer(index_type),
        K._fake_pointer(index_type),
        K._fake_pointer(Int32),
        K._fake_pointer(Int32),
        K._fake_pointer(Int32),
        K._fake_pointer(Int32),
        K._fake_pointer(cutlass.Int8),
        K._fake_pointer(Float32),
        K._fake_pointer(BFloat16),
        Int64(1),
        Int64(1),
        Int64(1),
        Int64(1),
        Int32(1),
        Int32(0),
        current_cuda_stream(),
        compile_spec=KernelCompileSpec.from_key("glm53.kda_prefill.recurrence_ckpt", 1, key),
    )

    def launch(active, ckpt: Checkpoints, window: int) -> None:
        if _recurrence_ckpt_key(active, ckpt.max_checkpoints) != key:
            raise ValueError("compiled KDA checkpoint recurrence kernel does not match the binding")
        raw(
            K._pointer(active.v, BFloat16),
            K._pointer(active.cu_seqlens, Int32),
            K._pointer(active.band_base, Int32),
            K._pointer(active.sorted_seq, Int32),
            K._pointer(active.window_table, Int32),
            K._pointer(active.initial_state_indices, index_type),
            K._pointer(active.final_state_indices, index_type),
            K._pointer(ckpt.slots, index_type),
            K._pointer(ckpt.offsets, Int32),
            K._pointer(active.num_seqs, Int32),
            K._pointer(active.error_code, Int32),
            K._pointer(active.ready_flags, Int32),
            K._pointer(active.ws.view(torch.int8), cutlass.Int8),
            K._pointer(active.recurrent_state, Float32),
            K._pointer(active.output, BFloat16),
            int(active.v.stride(0)),
            int(active.output.stride(0)),
            int(active.recurrent_state.stride(0)),
            int(active.final_state_indices.stride(0)),
            int(active.token_capacity),
            int(window),
            current_cuda_stream(),
        )

    _RECURRENCE_CKPT_CACHE[key] = launch
    return key, launch


def check_checkpoints(binding, ckpt: Checkpoints) -> None:
    """Host-side shape and dtype contract (the values are the planner's contract; trusted validation)."""
    if binding.plan.caps.metadata_validation != "trusted":
        raise ValueError("glm53_kda_ckpt runs under trusted metadata validation (b12x's prologue ignores checkpoints)")
    m = int(ckpt.max_checkpoints)
    if not 1 <= m <= MAX_CHECKPOINTS:
        raise ValueError(f"max_checkpoints must be in 1..{MAX_CHECKPOINTS}")
    seqs = int(binding.seq_capacity)
    for name, tensor, dtype in (("slots", ckpt.slots, binding.initial_state_indices.dtype),
                                ("offsets", ckpt.offsets, torch.int32)):
        if tuple(tensor.shape) != (seqs, m) or tensor.dtype != dtype or not tensor.is_contiguous():
            raise ValueError(f"checkpoint {name} must be a contiguous {dtype} [{seqs}, {m}] tensor, "
                             f"got {tuple(tensor.shape)} {tensor.dtype}")
        if tensor.device != binding.output.device:
            raise ValueError(f"checkpoint {name} must be on {binding.output.device}")


def _launch_recurrence_ckpt(binding, ckpt: Checkpoints, window: int) -> None:
    key = _recurrence_ckpt_key(binding, ckpt.max_checkpoints)
    launch = _RECURRENCE_CKPT_CACHE.get(key)
    capturing = torch.cuda.is_current_stream_capturing()
    if capturing and (launch is None or key not in _WARMED):
        raise RuntimeError("KDA checkpoint recurrence must be compiled and warm-run before CUDA graph capture")
    if launch is None:
        key, launch = _compile_recurrence_ckpt(binding, ckpt.max_checkpoints)
    launch(binding, ckpt, int(window))
    if not capturing:
        _WARMED.add(key)


def export_conv_history(conv_state_sd: torch.Tensor, x: torch.Tensor, ckpt: Checkpoints) -> None:
    """conv_state_sd[slot, j, :] = x[row, :] for every (row, slot, j) triple of the plan: the three pre-conv q|k|v rows
    before each checkpoint become that checkpoint's conv-state rows 0..2 (SD layout [slots, width, dim])."""
    if ckpt.conv_rows is None or ckpt.conv_rows.numel() == 0:
        return
    conv_state_sd[ckpt.conv_slots, ckpt.conv_cols] = x.index_select(0, ckpt.conv_rows)


def run_prefill_ckpt(binding, ckpt: Checkpoints, *, lower_bound: float, scale: float, eps: float,
                     windows: int, conv_x: torch.Tensor | None = None,
                     conv_state_sd: torch.Tensor | None = None) -> None:
    """b12x's window pipeline (K.run_prefill) with the checkpoint recurrence; the conv history is exported from
    ``conv_x`` (the pre-conv q|k|v rows) into ``conv_state_sd`` when both are given."""
    check_checkpoints(binding, ckpt)
    device = binding.output.device
    plan = binding.plan
    launched = int(windows)
    if launched < 1 or launched > plan.max_windows:
        raise ValueError(f"windows must be in 1..{plan.max_windows}, got {launched}")
    with torch.cuda.device(device):
        main = torch.cuda.current_stream(device)
        resources = K._side_resources(device, launched)
        side = resources.stream
        fork = resources.events[2 * launched]
        prepared = resources.events[:launched]
        consumed = resources.events[launched:2 * launched]
        K.run_prologue(binding, windows=launched)
        fork.record(main)
        side.wait_event(fork)

        def enqueue_prepare(window: int) -> None:
            with torch.cuda.stream(side):
                if window >= 2:
                    side.wait_event(consumed[window - 2])
                K.run_prepare(binding, lower_bound=lower_bound, scale=scale, eps=eps, window=window)
                prepared[window].record(side)

        enqueue_prepare(0)
        for window in range(launched):
            main.wait_event(prepared[window])
            _launch_recurrence_ckpt(binding, ckpt, window)
            consumed[window].record(main)
            if window + 1 < launched:
                enqueue_prepare(window + 1)
        if conv_x is not None and conv_state_sd is not None:
            export_conv_history(conv_state_sd, conv_x, ckpt)


def run_prefill_conv_fused_ckpt(binding, conv, ckpt: Checkpoints, *, lower_bound: float, scale: float, eps: float,
                                windows: int) -> None:
    """glm53_kda_conv.run_prefill_conv_fused with the checkpoint recurrence, then the conv history of every
    checkpoint (from ``conv.x``, the pre-conv q|k|v rows) after the conv-state update of the final slots."""
    import glm53_kda_conv as C

    check_checkpoints(binding, ckpt)
    device = binding.output.device
    plan = binding.plan
    launched = int(windows)
    if launched < 1 or launched > plan.max_windows:
        raise ValueError(f"windows must be in 1..{plan.max_windows}, got {launched}")
    if binding.v.data_ptr() != conv.v_out.data_ptr():
        raise ValueError("binding.v must view conv.v_out")
    with torch.cuda.device(device):
        main = torch.cuda.current_stream(device)
        resources = K._side_resources(device, launched)
        side = resources.stream
        fork = resources.events[2 * launched]
        prepared = resources.events[:launched]
        consumed = resources.events[launched:2 * launched]
        K.run_prologue(binding, windows=launched)
        fork.record(main)
        side.wait_event(fork)

        def enqueue_prepare(window: int) -> None:
            with torch.cuda.stream(side):
                if window >= 2:
                    side.wait_event(consumed[window - 2])
                K._launch_stage(
                    lambda b: (C._prepare_conv_key(b), C._PREPARE_CONV_CACHE.get(C._prepare_conv_key(b))),
                    C._compile_prepare_conv,
                    binding,
                    conv,
                    float(scale),
                    float(lower_bound) * _LOG2E,
                    float(eps),
                    int(window),
                )
                prepared[window].record(side)

        enqueue_prepare(0)
        for window in range(launched):
            main.wait_event(prepared[window])
            _launch_recurrence_ckpt(binding, ckpt, window)
            consumed[window].record(main)
            if window + 1 < launched:
                enqueue_prepare(window + 1)
        K._launch_stage(
            lambda b: (C._state_key(b, conv), C._STATE_CACHE.get(C._state_key(b, conv))),
            lambda b: C._compile_state(b, conv),
            binding,
            conv,
        )
        export_conv_history(conv.state_sd, conv.x, ckpt)


def make_checkpoints(per_seq, *, max_checkpoints: int, null_slot: int, device, index_dtype=torch.int32,
                     seq_starts=None, with_conv: bool = True) -> Checkpoints:
    """Host-side builder. ``per_seq``: one list per sequence of the call (the call's order) of (offset, slot) pairs,
    offsets relative to the sequence's first row of this call, multiples of 16, strictly inside its rows or at its
    end; ``seq_starts``: the sequences' first rows in the call (needed for the conv history)."""
    m = int(max_checkpoints)
    if not 1 <= m <= MAX_CHECKPOINTS:
        raise ValueError(f"max_checkpoints must be in 1..{MAX_CHECKPOINTS}")
    slots = [[int(null_slot)] * m for _ in per_seq]
    offsets = [[0] * m for _ in per_seq]
    rows, cslots, cols = [], [], []
    for s, pairs in enumerate(per_seq):
        if len(pairs) > m:
            raise ValueError(f"sequence {s} has {len(pairs)} checkpoints, more than {m}")
        seen = set()
        for c, (offset, slot) in enumerate(pairs):
            offset, slot = int(offset), int(slot)
            if offset <= 0 or offset % _CHUNK or slot == int(null_slot) or slot in seen:
                raise ValueError(f"sequence {s}: bad checkpoint (offset {offset}, slot {slot})")
            seen.add(slot)
            slots[s][c], offsets[s][c] = slot, offset
            if with_conv:
                if seq_starts is None:
                    raise ValueError("seq_starts is required for the conv history")
                for j in range(3):
                    rows.append(int(seq_starts[s]) + offset - 3 + j)
                    cslots.append(slot)
                    cols.append(j)
    ckpt = Checkpoints(
        slots=torch.tensor(slots, dtype=index_dtype).to(device, non_blocking=True),
        offsets=torch.tensor(offsets, dtype=torch.int32).to(device, non_blocking=True),
        max_checkpoints=m,
    )
    if with_conv and rows:
        ckpt.conv_rows = torch.tensor(rows, dtype=torch.int64).to(device, non_blocking=True)
        ckpt.conv_slots = torch.tensor(cslots, dtype=torch.int64).to(device, non_blocking=True)
        ckpt.conv_cols = torch.tensor(cols, dtype=torch.int64).to(device, non_blocking=True)
    return ckpt


def _bind(layer, *, q, k, v, raw_g, raw_beta, cu_seqlens, state_indices, has_initial_state, recurrent_state,
          scratch, output):
    """kda.py's binding of ``_run_b12x_kda_prefill`` (same plan, metadata buffers and index masking)."""
    api = layer._b12x_prefill_api
    plan = layer._b12x_prefill_plan
    if api is None or plan is None:
        raise RuntimeError("b12x KDA prefill KV cache was not bound before inference")
    num_tokens = int(q.shape[0])
    num_requests = int(state_indices.shape[0])
    if num_tokens > layer._b12x_prefill_max_tokens or num_requests > layer._b12x_prefill_max_seqs:
        raise ValueError(
            "b12x KDA prefill capacity exceeded: "
            f"tokens={num_tokens}/{layer._b12x_prefill_max_tokens}, "
            f"requests={num_requests}/{layer._b12x_prefill_max_seqs}"
        )
    initial_indices = layer._b12x_prefill_initial_indices[:num_requests]
    initial_indices.copy_(state_indices)
    initial_indices.masked_fill_(~has_initial_state[:num_requests], plan.caps.null_state_index)
    layer._b12x_prefill_num_seqs.fill_(num_requests)
    layer._b12x_prefill_num_tokens.fill_(num_tokens)
    binding = api.bind(
        plan,
        scratch=scratch,
        q=q,
        k=k,
        v=v,
        raw_g=raw_g,
        raw_beta=raw_beta,
        A_log=layer.A_log.view(-1),
        dt_bias=layer.dt_bias.view(-1, layer.head_dim),
        recurrent_state=recurrent_state,
        cu_seqlens=cu_seqlens[: num_requests + 1],
        initial_state_indices=initial_indices,
        final_state_indices=state_indices,
        checkpoint_state_indices=layer._b12x_prefill_null_indices[:num_requests],
        checkpoint_offsets=layer._b12x_prefill_zero_offsets[:num_requests],
        num_seqs=layer._b12x_prefill_num_seqs,
        num_tokens=layer._b12x_prefill_num_tokens,
        output=output,
    )
    return binding, plan.launched_windows(num_tokens, num_requests)


def run_kda_prefill_ckpt(layer, *, q, k, v, raw_g, raw_beta, cu_seqlens, state_indices, has_initial_state,
                         recurrent_state, scratch, output, ckpt: Checkpoints, conv_x=None, conv_state_sd=None) -> None:
    """kda.py's ``_run_b12x_kda_prefill`` (b12x's own prepare on post-conv q/k/v) with the checkpoint recurrence; the
    conv history comes from ``conv_x`` (pre-conv q|k|v rows) into ``conv_state_sd`` (SD layout)."""
    binding, windows = _bind(layer, q=q, k=k, v=v, raw_g=raw_g, raw_beta=raw_beta, cu_seqlens=cu_seqlens,
                             state_indices=state_indices, has_initial_state=has_initial_state,
                             recurrent_state=recurrent_state, scratch=scratch, output=output)
    run_prefill_ckpt(binding, ckpt, lower_bound=float(layer.kda_lower_bound), scale=float(layer.head_dim) ** -0.5,
                     eps=1e-6, windows=windows, conv_x=conv_x, conv_state_sd=conv_state_sd)


def run_kda_prefill_conv_fused_ckpt(layer, *, qkv, conv_weight, conv_state_sd, raw_g, raw_beta, cu_seqlens,
                                    state_indices, has_initial_state, recurrent_state, scratch, output, v_out,
                                    ckpt: Checkpoints) -> None:
    """glm53_kda_conv.run_kda_prefill_conv_fused with the checkpoint recurrence and the checkpoints' conv history."""
    import glm53_kda_conv as C

    num_tokens = int(qkv.shape[0])
    heads, head_dim = layer.local_num_heads, layer.head_dim
    proj = heads * head_dim
    v_rows = v_out[:num_tokens]
    binding, windows = _bind(layer, q=qkv[:, :proj].view(num_tokens, heads, head_dim),
                             k=qkv[:, proj:2 * proj].view(num_tokens, heads, head_dim),
                             v=v_rows.view(num_tokens, heads, head_dim), raw_g=raw_g, raw_beta=raw_beta,
                             cu_seqlens=cu_seqlens, state_indices=state_indices, has_initial_state=has_initial_state,
                             recurrent_state=recurrent_state, scratch=scratch, output=output)
    run_prefill_conv_fused_ckpt(binding, C.ConvArgs(qkv, conv_weight, conv_state_sd, v_rows), ckpt,
                                lower_bound=float(layer.kda_lower_bound), scale=float(head_dim) ** -0.5, eps=1e-6,
                                windows=windows)


def prewarm(binding, max_checkpoints: int) -> None:
    """Compile the checkpoint recurrence for ``binding`` (b12x's prologue and prepare are b12x's own)."""
    with torch.cuda.device(binding.output.device):
        _compile_recurrence_ckpt(binding, max_checkpoints)


__all__ = ["Checkpoints", "MAX_CHECKPOINTS", "check_checkpoints", "export_conv_history", "make_checkpoints", "prewarm",
           "run_kda_prefill_ckpt", "run_kda_prefill_conv_fused_ckpt", "run_prefill_ckpt", "run_prefill_conv_fused_ckpt"]
