# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Contributors to this repository
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Emit complete required tool objects once, independently of chunk layout."""
REPLACEMENT = 'def _completed_required_tools(text: str | None) -> list[dict]:\n    """Read complete tool objects from an unfinished JSON array.\n\n    Required tool arguments are emitted atomically per completed object. This\n    avoids partial-JSON repairs changing escapes or assigning an old object\'s\n    tail to a newly started array index when a delta crosses tool boundaries.\n    """\n    if not text:\n        return []\n    decoder = json.JSONDecoder()\n    pos = len(text) - len(text.lstrip())\n    if pos >= len(text) or text[pos] != "[":\n        return []\n    pos += 1\n    result = []\n    while True:\n        while pos < len(text) and text[pos].isspace():\n            pos += 1\n        if pos >= len(text) or text[pos] == "]":\n            return result\n        try:\n            obj, end = decoder.raw_decode(text, pos)\n        except json.JSONDecodeError:\n            return result\n        if not isinstance(obj, dict) or not isinstance(obj.get("name"), str):\n            return result\n        if "parameters" not in obj:\n            return result\n        result.append(obj)\n        pos = end\n        while pos < len(text) and text[pos].isspace():\n            pos += 1\n        if pos >= len(text) or text[pos] != ",":\n            return result\n        pos += 1\n\n\ndef extract_required_tool_call_streaming(\n    *,\n    previous_text: str,\n    current_text: str | None,\n    delta_text: str,\n    function_name_returned: bool,\n    tool_call_idx: int | None,\n    tool_call_id_type: str,\n) -> tuple[DeltaMessage | None, bool]:\n    previous = _completed_required_tools(previous_text)\n    current = _completed_required_tools(current_text)\n    calls = []\n    for index in range(len(previous), len(current)):\n        obj = current[index]\n        calls.append(DeltaToolCall(\n            id=make_tool_call_id(\n                id_type=tool_call_id_type,\n                func_name=obj["name"],\n                idx=None if tool_call_idx is None else tool_call_idx + index - len(previous),\n            ),\n            type="function",\n            index=index,\n            function=DeltaFunctionCall(\n                name=obj["name"],\n                arguments=json.dumps(obj["parameters"], ensure_ascii=False),\n            ),\n        ))\n    return (DeltaMessage(tool_calls=calls) if calls else None,\n            function_name_returned or bool(calls))\n'

def transform(source):
    anchor="def extract_required_tool_call_streaming("
    if source.count(anchor)!=1:raise RuntimeError("Required-tool helper anchor mismatch")
    start=source.index(anchor)
    if any(line.startswith("def ") for line in source[start:].splitlines()[1:]):
        raise RuntimeError("Unexpected declaration after required-tool helper")
    return source[:start]+REPLACEMENT
